version: '2'

networks:
  custom:
    driver: bridge

services:
  controller:
    build: ./codebox
    image: codebox
    ports:
      - "80:8000"
    environment:
      CODEBOX_USERNAME: admin
      CODEBOX_PASSWORD: 1nitCr0n
    volumes:
      - /mnt/codebox:/workspace
    networks:
      - custom
    container_name: controller
 
  app:
    build: ./centos-node
    image: centos-node
    container_name: app
    ports:
       - "8080:22"
    networks:
      - custom
    container_name: app

  web:
    i mage: centos-node
    ports:
       - "8081:22"
    networks:
      - custom
    container_name: web
  
  db:
    image: centos-node
    ports:
       - "8082:22"
    networks:
      - custom
    container_name: db

  lb:
    build: ./ubuntu-node
    image: ubuntu-node
    ports:
       - "8083:22"
    networks:
      - custom
    container_name: lb
